n = input('Digite algo: ')
print('O tipo primitivo desse valor é: ',type(n))
print('Só tem espaços? ',n.isspace())
print('É um número? ',n.isnumeric())
print('É alfabético? ',n.isalpha())
print('É alfanumérico? ',n.isalnum())
print('Tem maiúsculas? ',n.isupper())
print('Tem minúsculas? ',n.islower())
print('É capitalizada? ',n.istitle())
